### ISSUE TITLE
Erro ao executar o comando

### ISSUE THREAD

**Issue by davidalves1** [diogomoretti/velocidade#1]
Ocorreu o seguinte erro ao executar o comando ```$ velocidade```:

```terminal
$ velocidade
/ Verificando sua conexão de internet...events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotConfig (C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\speedtest-net\index.js:510:20)
    at C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\speedtest-net\index.js:48:16
    at C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\speedtest-net\index.js:241:7
    at Parser.<anonymous> (C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\xml2js\lib\xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.exports.Parser.Parser.parseString (C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\xml2js\lib\xml2js.js:499:16)
    at Parser.parseString (C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\xml2js\lib\xml2js.js:7:59)
    at exports.parseString (C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\xml2js\lib\xml2js.js:540:19)
    at C:\Users\David\AppData\Roaming\npm\node_modules\velocidade\node_modules\speedtest-net\index.js:239:5
```

**Comment by diogomoretti** [comment]
Olá @davidalves1,

O dólar `$` no início do comando é só pra simbolizar o uso do terminal/bash. O comando é só `valocidade`. Dá uma testada ai e me diz.

**Comment by diogomoretti** [comment]
Olá @davidalves1, parece um erro na lib do speedtest. Já tem issue aberta lá (https://github.com/ddsol/speedtest.net/issues/33) e um PR corrigindo isso (https://github.com/ddsol/speedtest.net/pull/34). Assim que lançarem nova versão, atualizo aqui.

**Comment by diogomoretti** [comment]
Os caras arrumaram. Dá um update (`[sudo] npm update -g velocidade`) e tenta ai =]
